### ISSUE TITLE
Object#timeout is deprecated

### ISSUE THREAD

**Issue by nnsaln** [sensu-plugins/sensu-plugins-ansible#3]
"output":["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:134:in `block in filter_silenced': Object#timeout is deprecated, use Timeout.timeout instead.

**Comment by cwjohnston** [comment]
Version 0.0.4 of this project changes the sensu-plugin constraint from `=1.2.0` to `~> 1.2`, enabling the use of newer versions of sensu-plugin (e.g. 1.3.0) which address the deprecation warning you describe.
